const initialCart = [
    {product: { id: 1, name: "1610 Pure Cotton Summer Tshirt", category: "Men", price: 500, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Csimply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letr", reviews: [{ reviewerName: "", reviewDesc: "", rating: 3 }, { reviewerName: "", reviewDesc: "", rating: 4 }], images: ["http://res.cloudinary.com/deo80u7qs/image/upload/v1687442791/jamneknds0sxyjcc7bgf.png", "http://res.cloudinary.com/deo80u7qs/image/upload/v1687442791/jamneknds0sxyjcc7bgf.png", "http://res.cloudinary.com/deo80u7qs/image/upload/v1687442791/jamneknds0sxyjcc7bgf.png", "http://res.cloudinary.com/deo80u7qs/image/upload/v1687446643/iikompwpmmoefqaqr5e0.jpg"] }, selectedSize: "S",quantity: 3 },
    {product: { id: 2, name: "T-shirt", category: "Men", price: 500, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{ reviewerName: "", reviewDesc: "", rating: 3 }, { reviewerName: "", reviewDesc: "", rating: 3 }], images: [""] }, selectedSize: "L", quantity: 2}]

 const products = [
    { id: 1, name: "1610 Pure Cotton Summer Tshirt", category: "Men", price: 500, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Csimply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letr", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 4}], images: ["http://res.cloudinary.com/deo80u7qs/image/upload/v1687442791/jamneknds0sxyjcc7bgf.png","http://res.cloudinary.com/deo80u7qs/image/upload/v1687442791/jamneknds0sxyjcc7bgf.png","http://res.cloudinary.com/deo80u7qs/image/upload/v1687442791/jamneknds0sxyjcc7bgf.png","http://res.cloudinary.com/deo80u7qs/image/upload/v1687446643/iikompwpmmoefqaqr5e0.jpg"] },
    { id: 2, name: "T-shirt", category: "Men", price: 500, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 3, name: "T-shirt", category: "Men", price: 500, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 4, name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 5, name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 6, name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 7, name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 8, name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 9, name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 10, name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 11, name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 12, name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 13, name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 14, name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 15, name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 16, name: "Track Pants", category: "Sports", price: 700, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 17, name: "Track Pants", category: "Sports", price: 700, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 18, name: "Track Pants", category: "Sports", price: 700, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 19, name: "Track Pants", category: "Sports", price: 700, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 20, name: "Shorts", category: "Casual", price: 200, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 21, name: "Shorts", category: "Casual", price: 200, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: 22, name: "Shorts", category: "Casual", price: 200, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] }

 ]

 export {initialCart, products}