import { nanoid } from "@reduxjs/toolkit"

export const products = [
    { id: nanoid(), name: "1610", category: "Men", price: 500, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Cotton Summer T-shirt", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 4}], images: [""] },
    { id: nanoid(), name: "T-shirt", category: "Men", price: 500, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "T-shirt", category: "Men", price: 500, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Saree", category: "Women", price: 800, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Baba Suit", category: "Kids", price: 1000, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Track Pants", category: "Sports", price: 700, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Track Pants", category: "Sports", price: 700, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Track Pants", category: "Sports", price: 700, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Track Pants", category: "Sports", price: 700, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Shorts", category: "Casual", price: 200, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Shorts", category: "Casual", price: 200, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] },
    { id: nanoid(), name: "Shorts", category: "Casual", price: 200, stock: 100, noOfPurchases: 3, size: ["XS", "S", "M", "L", "XL"], desc: "Description", reviews: [{reviewerName: "", reviewDesc: "", rating: 3},{reviewerName: "", reviewDesc: "", rating: 3}], images: [""] }

]